### ISSUE TITLE
enumSum?

### ISSUE THREAD

**Issue by f-f** [garyb/purescript-codec-json#2]
I just noticed that [`enumSum`](https://pursuit.purescript.org/packages/purescript-codec-argonaut/10.0.0/docs/Data.Codec.Argonaut.Sum#v:enumSum) didn't make it - is there a reason for leaving it out, or is it fine to port here?

**Comment by garyb** [comment]
No good reason for it to be missing that I can think of, I'm not sure why I didn't carry it over!
